### ISSUE TITLE
Unable to run flask shell

### ISSUE THREAD

**Issue by rajsinghtech** [jperezsan/meraki-webapp-flask#1]
Traceback (most recent call last):
  File "C:\Users\kingr\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kingr\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code       
    exec(code, run_globals)
  File "C:\Users\kingr\Documents\GitHub\meraki-webapp-flask\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\flask\cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\flask\cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\flask\cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\flask\cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "c:\users\kingr\documents\github\meraki-webapp-flask\venv\lib\site-packages\flask\cli.py", line 117, in call_factory
    return app_factory(script_info)
  File "C:\Users\kingr\Documents\GitHub\meraki-webapp-flask\app\__init__.py", line 22, in create_app     
    app.config.from_object(config[config_name])
KeyError: <flask.cli.ScriptInfo object at 0x000002409FCEBAC0>

**Comment by jperezsan** [comment]
Can you share with me which steps did you follow to run the app?
Are you trying to run the app on Windows or Linux?
